name: Nightwatch Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: sudo apt-get install xvfb
    
    - name: Run Nightwatch tests
      run: xvfb-run --auto-servernum npm run nightwatch -- --env chrome

    # - name: Run Nightwatch tests
    #   run: npx nightwatch ./nightwatch/examples/twoshipstest/*.js --headless