name: Nightwatch Tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Install live-server
      run: npm install -g live-server
       
    - name: Install Chromedriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        curl -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        mv chromedriver /usr/local/bin/

    - name: Start Live Server
      run: live-server --port=5500 --watch="./index.html" &

    - name: Start Live Server with XVFB
      run: xvfb-run --server-args="-screen 0 1024x768x24" live-server --port=5500 --watch="./index.html" &
    
    - name: Run Nightwatch
      run: npm run nightwatch

    - name: Stop Live Server
      run: pkill -f "live-server"
    # - name: Run Nightwatch tests
    #   run: xvfb-run --auto-servernum npm run nightwatch:headless -- --env chrome

    # - name: Run Nightwatch tests
    #   run: npx nightwatch ./nightwatch/examples/twoshipstest/*.js --headless